spring:
  applivation:
    name: Config-Default




eureka:
 instance:
  prefer-ip-address: true
    
  client:
    fetchRegistry: true
    register-with-eureka: true
    service-url:
    defaultZone: http://localhost:8761/eureka
